apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: dependency
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./4_08/apps
  prune: true
  validation: client