apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: project-secret
  namespace: default
spec:
  dependsOn:
    - name: infrastructure
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./4_08/secrets
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
      namespace: default