apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: project-secret
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: project-secret
  path: ./4_08/secrets
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age