apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: project-secret
  namespace: project-namespace
spec:
  encryptedData:
    DISCORD_URL: AgCZCp2Z9mKwmou7rlE8xt5e0TTF/34HlccN4ymeqpYPlX650lwJ3lE4FORUnMu+kIAFuclPqL4DMOEGX7gHryY5IUr6QkQm6+lhFhQok50qQVGlaeaJXtIW6dw2Km9KZXwBVVLAFWNskZquxJbfr5HSO1Bww10Dx6A+KuFLmqB+BIeHhntR2lwO/mhhyrHyJ5Nwf4GdsZhCn0j+c384/Ti2elm4uWswJDDmqo0IOplL0F3ZM7DjjluA5BcMcEM50ZdinJEy3HsSH8i4UgdhqAfjSDrY3IO7E6yIe7ZmDgn2SkEk+yV7T8HMZh0cU2CWRceJnf3uEUGfUZ8jzhTZ8Ji1gjpr8aBb+kzG2fhNJ3tBHlgs0adxuOcsxybcdYnmOiMjaf8y3g3eY2dSuvG1TUsqmLYwh0KLzRgnPprwsZFSYiK2TI4XnoZcfkZatw8Iudm41gX+/WiiAaHYtIZ1PvPEXuBnBJfO1uWSP/NiYIHbnSTY7gmSvg2OgpsM2VPgD14crZ/cSIhY5EyO5VCwl4yFKYvAk1njNUeupUGRPBTW/+CnO6yXVF9dRPPol7SbpzTpXQJJEVt7RQQWX11bxPZ75ndnJQSHi5veXZChsazFzNQlcQizMPnu+0VKoyo8JWFydnEoj8RuI3+qsSaQk+N0M6SKfzpSnSL/zlLylPH+Ry6kuoPOLRZMq3QSM5s0AEA7DL3uexBlN61OzMcXbl5/6vR9hF/AY5+R8l2UY6LeQ27YprmZs6RtSCptiBX6QtRGM9sq4b7MRHHnYmUMMaO5x/+v9WFrgM5AWFbHP9EUGFvulVfA8bjmm8iTjhhjZ9YoJLhgTdzdVFSSlSIuX945DutgIHo8we4=
    POSTGRES_PASSWORD: AgCkusJkcAoFlF9uP/zIxZevwybK1klRxSqz/JO2cC1+n37aS6fB0gN9mbxX5NOiJDvhyS9878GJn1OVXHI+iOAzVof2aTo9CPRABGfKcbbjek3qJSxJCrlq3qU79gjZjfVD2C3D++EEyYA5Wq6Ne1wEUQS1+3Onm+UArMEKScmhU5FnHM+1kGEOKBkhbQYgys3hjnOL9CA+ATSu/vIY/Jisc1x78YYe4S77svHNri1ai/RrYlsmZPaM8hpvbTjqJlwszf5jVgxNQLW4/Fm+xYKQXip+eC171SdDA+BOtivUnlLP5KuscbtE5tLUvgFc7KmHCN8Bzyxz7z4Alkys72ugOOUygRtocRPuU5awCp2bUNxru4qu54A+rnMw3mirtCOb1QP1zeHJa6BJ477bU752Ktd/ehntqDwM6tYnaGrWnrtRJrDHbzyDaeFXdKKArZeLB9zSNX0Ckw8phgPSMbBIaRoACYs7TP1FGeo7vxDqkxf2qP+5ZMZWkIes3nGx63k5nB8c9hI5EA3/8X4ewWi1hsizu0QMGEnk+E3OyNxLfR2RoJdMCVYuaAIypeKObSOaxzRC7emLACk+qEs6mkoeOx8t8AXd/O/ALzG7y+eaF252qKojp104VqaILlfFz3witZzGXLuWF3frta3UxmJtO5cm0/SmM5j5jjVEYVZG8cE4K/lsu2pirwsjDHPAFiocJcin
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: project-secret
      namespace: project-namespace

