apiVersion: v1
kind: Secret
metadata:
    name: project-secret
    namespace: project-namespace
data:
    #ENC[AES256_GCM,data:tSD/R1B0EM7K+h+yrRIy,iv:c+IKlE2r7O5j6Q2n/hu1hddTnSuC7mzqG7HVVaxurkM=,tag:qYN3skPp4pHkwhOVCu+sJg==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:3yRfLA0c6gI=,iv:1WqWmg/5oF26LltLN5JzT96y9/uoE6NMn/0Z3jI1cMw=,tag:5CoFdwoghRTsYuTn/lZzUA==,type:str]
    DISCORD_URL: ENC[AES256_GCM,data:PEfvy85OCeh9QvEgvjieM+BX1PWRyvC2CfpA7DzxdKJkerQRrOciRPNZ7gb8es32y/zzL+Hb9NuVV2JoEElqNvVWPMMiavVrce6K91wEqvniODDFwk7xMfUTRF5rZYtByeYpFEnuq07EL/U2QNaEAi+gKpuJU2l4W09uUeBQ6TmO57tja2lsWCnph70y4ETW0ufY3wp2UOIKBLwAibI7iQ==,iv:Ul4kv2iLARHeY16Olzrf5xOKiJiQgorbrKk14aT1SHA=,tag:EP/lkCGBBbpCKK6U+Z05VQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rdhunmgqxcxnnzmllanuws530axkjwlvr82yjh8yxfchpp85qezsgjg8ga
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcWxhZ25IOHloOHQ4cUxO
            WTNiUXM0VmhwRzdpVDN5R2ZZM3dkUklIem5nCnhwb1FnSHRwM084VG1Iaitzbk9z
            Q2RCTUI2SEdWNkdKQjlZOWIrRmdjbEEKLS0tIFlIZkNjS2hnUGVzV3FIdFRUbXhE
            YWVkYlZTUmxuSmRUcWd3Q2VUUWxHdzAKq4++pIMHiQq6E2tFHPrWyB8N9tDF9RBJ
            R6bimwxXZc0Zyuu33rvfAuMQo8gY4/M6ZOq/YR/csJC6HRDwtuZMvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-22T12:33:17Z"
    mac: ENC[AES256_GCM,data:QF5LzrtNJne7v4jTv3Ojw7t+TygaOrsHtst6mJ6Ql1k3HhjtIBPVsSgcHz3nXtPnsGNKUSn3mdcidCAIdN0cReRuftHU8TPZN3B7oSfIBV/TNWnVvZcE1rD3jzX99lSOn7bInkr0iwWEc6QeVRFqVVsqF7bfYkyvi0JsgbddC8Y=,iv:rjwosLiXUQHCIEix2v+m8gG928ZHJeULXx2kmsRtchw=,tag:wxVT3BbbsHzXxYFmfkxaRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
