apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: flux-system
spec:
  releaseName: my-nats
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
      version: "0.9.2"
  interval: 1h
  targetNamespace: default
  install:
    remediation:
      retries: 3
