apiVersion: v1
kind: Secret
metadata:
    name: project-secret
    namespace: project-namespace
data:
    #ENC[AES256_GCM,data:o7V1v6t8RggKnYHUHd4s,iv:ov6DjksAHDDd8svVJyUXliSkhJBj39373SVm1C7JsNU=,tag:01iYsSMqUZWT4sr3AJu2hw==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:9g7uL2NF2Js=,iv:kYPO9MpN3s1wjasW5lZZpX1WgDaM2jdYAwPmyv+GOqk=,tag:NQQCt/PYDEXxvlYK++Nppg==,type:str]
    DISCORD_URL: ENC[AES256_GCM,data:IjAXZk+706KiX6yPB5UDdwTUFFn4hGQ8o+MuPPkGBEtK+Y0bYn44AP9GC0mrlk1Q2jhOf4nOcd/MuUC7wDZaOSkuRx4NIcn94Ohm5ZMv98YBNuIY6gZsFWijXLZunsvsKKdgHDSulDV3cW0uDvP0fQpcGEGE9qOMe2lj2vIN9F9b99W+OKlNhm4C+ZVAWquKkDQnIjwuPvH0Cz2C49GLgw==,iv:EDKJj/gJrVsZ7ZBOJrqZ2sS9BlpSeb1d6MMBWRJOc8o=,tag:+Cmp0hkwF0BI5Sj+dwtUqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w9vk0g8zu6u0y79tnpxv08yfvd8eem8w5yqvhry5q4k35xh2talqmyevey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVEZyV3pHdTVYdFF3QlJT
            Z0huRjg0NEpYeFpjQ2p6VUNOTjJWWXBxWENRCk9hbDNsdXBkeDFkUDFHWENHS29w
            Q042Y1NUTFhRUWovWlc0MUFObjdzUTQKLS0tIEhkWVU4a2N0a0JsUlBKYXlPV3J4
            WUEzaUwyaHFjbFVuamp1U1ovTXVLNHcKE5Atu6gNZBiI5rwDtXQsCRqI4IcqeOSi
            3cahsi6UWA41M9tYY0e5UBLMGtbKkcJaQsoC38TFdnS4vLD3IsjT0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-22T16:17:12Z"
    mac: ENC[AES256_GCM,data:yNB76JAqlRD1TOGGBAdGVvSNE2X5W4Nf35nDKglBQVjlVPW3jwwxVERYHHE+dCgletrr0s7bTeNf14+8OxarN4NFY0kXaoFTiPzlB3tBpcSdMbnuVhb51QASAHEVjnGs8lYTSUIXuXNZX5sEGtngvge6uMWLafrtH1WNQ4QRT18=,iv:/q5iO0pGIi7iq3TD77d+V1q0y6j8QpCE7WLtQEoU+wY=,tag:VZwSdbOrbWfIrWer0mNVPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
